---

- name: mkdir backup
  command: sudo mkdir ~/backup
  args:
    creates: ~/backup

- name: chmod backup dir
  command: sudo chmod -R 777 ~/backup

- name: dumping mongodb data
  command: sudo mongodump --db {{database_name}} --out ~/backup/mongodb

- name: rar mongodb data
  command: tar -czvf ~/backup/storagon.tar.gz -C ~/backup/mongodb .

  #remember to create and chmod folder /home/backup/ in ansible tower host
- name: fetching mongodb data file to ansible tower host
  fetch: src=~/backup/storagon.tar.gz dest=/home/backup/{{ ansible_hostname }}/ flat=yes