---

- name: mkdir backup
  command: sudo mkdir ~/backup
  args:
    creates: ~/backup

- name: chmod backup dir
  command: sudo chmod -R 777 ~/backup

- name: dumping mysql data
  shell: sudo mysqldump --user={{mysql_user}} -p{{mysql_password}} {{database_name}} > ~/backup/storagon.sql

- name: fetching mysql data file to ansible tower host
  fetch: src=~/backup/storagon.sql dest=/home/{{ ansible_hostname }}/ flat=yes