---

- name: mkdir backup
  command: sudo mkdir ~/backup
  args:
    creates: ~/backup

- name: chmod backup dir
  command: sudo chmod -R 777 ~/backup

- name: dumping mongodb data
  command: sudo mongodump --db {{database_name}} --out backup/mongodb
  args:
    chdir: ~

- name: rar mongodb data
  command: tar -czvf backup/storagon.tar backup/mongodb
  args:
    chdir: ~

- name: fetching mongodb data file to ansible tower host
  fetch: src=~/backup/storagon.tar dest=/home/{{ ansible_hostname }}/ flat=yes