---

- name: mkdir backup
  file: path=/home/backup/ state=directory mode=0777
  sudo: yes

- name: get_date_time
  set_fact: mydate="{{lookup('pipe','date +%Y-%m-%d_%H%M')}}"

- name: dumping mysql
  shell: mysqldump --user={{mysql_user}} -p{{mysql_password}} {{database_name}} > /home/backup/Dump_{{ ansible_hostname }}_{{ mydate }}.sql

- name: create archive
  command: chdir=/home/backup/ tar -cvzf Dump_{{ ansible_hostname }}_{{ mydate }}.sql.tar.gz Dump_{{ ansible_hostname }}_{{ mydate }}.sql

- name: delete SQl dump file
  file: path=/home/backup/Dump_{{ ansible_hostname }}_{{ mydate }}.sql state=absent

- name: fetching mysql data file to ansible tower host
  fetch: src=/home/backup/Dump_{{ ansible_hostname }}_{{ mydate }}.sql.tar.gz dest={{ sql_fetch_path }} flat=yes

- name: delete tar file
  file: path=/home/backup/Dump_{{ ansible_hostname }}_{{ mydate }}.sql.tar.gz state=absent
