---

- name: transfering libowfat source code
  copy: src=files/opentracker/libowfat.zip dest=~/libowfat.zip

- name: transfering opentracker source code
  copy: src=files/opentracker/opentracker.zip dest=~/opentracker.zip

- name: unzip libowfat source code
  command: unzip ~/libowfat.zip
  args:
    creates: ~/libowfat

- name: unzip opentracker source code
  command: unzip ~/opentracker.zip
  args:
    creates: ~/opentracker

- name: make libowfat from source
  command: make
  args:
    chdir: ~/libowfat
    creates: ~/libowfat/open.a

- name: make opentracker from source
  command: make
  args:
    chdir: ~/opentracker
    creates: ~/opentracker/opentracker

- name: link opentracker
  file: src=~/opentracker/opentracker  dest=/usr/bin/opentracker state=link
  sudo: yes
  args:
    chdir: '{{ ansible_env.HOME }}'
    creates: /usr/local/bin/opentracker

- name: install mktorrent
  yum: name=mktorrent state=latest
  sudo: yes