---

- name: get and phantomjs file
  fetch: src=files/phantomjs-2.1.1-linux-x86_64.tar.bz2 dest=/tmp/
  
- name: unarchive phantomjs file
  unarchive: src=/tmp/phantomjs-2.1.1-linux-x86_64.tar.bz2 dest=/usr/local/
  args:
    creates: /var/www/projectforce/{{ phantomjs_version }}/
  sudo: yes

- name: create symlink phantomjs
  file:
    src=/usr/local/phantomjs-{{ phantomjs_version }}/bin/phantomjs
    dest=/usr/bin/phantomjs
    owner=root
    group=root
    state=link
  sudo: yes
