---

- name: add mongodb repo
  copy: src=files/mongodb.repo dest=/etc/yum.repos.d/mongodb.repo owner=root group=root mode=0644
  sudo: yes

- name: install mongodb
  yum: name=mongodb-org state=latest
  sudo: yes

- name: start and enable mongod service
  service: name=mongod state=started enabled=yes
  sudo: yes

- name: install mongodb python driver using pip
  pip: name=pymongo version=2.8
  sudo: yes

- name: install mongoengine ORM
  pip: name=mongoengine version=0.8.7
  sudo: yes
