---

- name: add nginx uptodate repo
  copy: src=files/nginx.repo dest=/etc/yum.repos.d/nginx.repo owner=root group=root mode=0644
  sudo: yes

- name: install nginx
  yum: name=nginx state=latest
  sudo: yes

- name: copy nginx configuration using other port
  template: src=templates/nginx/nginx.conf dest=/etc/nginx/nginx.conf
  sudo: yes

- name: copy default configuration using other port
  template: src=templates/nginx/default.conf dest=/etc/nginx/conf.d/default.conf
  sudo: yes

- name: mkdir var/lib/nginx dir
  command: sudo mkdir /var/lib/nginx/
  args:
    creates: /var/lib/nginx

- name: chmod var/lib/nginx dir
  command: sudo chmod -R 777 /var/lib/nginx/

- name: start and enable nginx service
  service: name=nginx state=started enabled=yes
  sudo: yes

- name: open listen port/tcp
  firewalld: zone=public port={{ nginx_port }}/tcp permanent=true state=enabled immediate=true
  sudo: yes