---

- name: install nginx
  yum: name=nginx state=latest
  sudo: yes

- name: copy nginx configuration using other port
  template: src=templates/nginx/default.conf dest=/etc/nginx/conf.d/default.conf
  sudo: yes

- name: start and enable nginx service
  service: name=nginx state=started enabled=yes
  sudo: yes

- name: open listen port/tcp
  firewalld: zone=public port={{ nginx_port }}/tcp permanent=true state=enabled immediate=true
  sudo: yes