---

- name: fetch file from remote host
  fetch: src=file/epel-release-7-5.noarch.rpm dest=/tmp/

- name: install epel package
  command: yum install /tmp/epel-release-7-5.noarch.rpm
  sudo: yes

- name: update package
  command: yum update
  sudo: yes
    