
- name: Download and link phantonjs file
  hosts: all
  vars:
    phantomjs_version: 2.1.1-linux-x86_64
  tasks:

    - name: Download and ectract file
      unarchive:
        src=https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-{{ phantomjs_version }}.tar.bz2
        dest=/usr/local/
        copy=no
      args:
        creates: /usr/local/phantomjs-{{ phantomjs_version }}/
      sudo: yes

    - name: create symlink phantomjs
      file:
        src=/usr/local/phantomjs-{{ phantomjs_version }}/bin/phantomjs
        dest=/usr/bin/phantomjs
        owner=root
        group=root
        state=link
      sudo: yes
