---

- name: create  jython folder
  file: path=/var/www/projectforce/jython/bin/ state=directory
  sudo: yes

- name: create phantomjs folder
  file: path=/var/www/projectforce/phantomjs/bin/ state=directory
  sudo: yes

- name: link jython to projectforce
  command: ln -s /usr/local/jython/bin/jython /var/www/projectforce/jython/bin/jython
  args:
    creates: /var/www/projectforce/jython/bin/jython
  sudo: yes

- name: link phantomjs to projectforce
  command: ln -s /usr/local/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /var/www/projectforce/phantomjs/bin/phantomjs
  args:
    creates: /var/www/projectforce/phantomjs/bin/phantomjs
  sudo: yes

- name: create /opt/wkhtmltox/bin/ folder
  file: path=/opt/wkhtmltox/bin/ state=directory
  sudo: yes

- name: link wkhtmltopdf to opt
  command: ln -s /usr/bin/wkhtmltopdfs /opt/wkhtmltox/bin/wkhtmltopdf
  args:
    creates: /opt/wkhtmltox/bin/wkhtmltopdf
  sudo: yes
