---

- stat: path=/var/www/{{ project_name }}/{{ sql_file_name }} 
  register: sql

- name: extract extract sql dump from tar file
  unarchive: src={{ path_sql_tar_file }} dest=/var/www/{{ project_name }} copy=yes
  when: not sql.stat.exists
  sudo: yes

- name: restore data from sql dump file
  shell: chdir=/var/www/{{ project_name }} python manage.py dbshell < {{ sql_file_name }}
  sudo: yes

- name: remove sql dump file
  file: path=/var/www/{{ project_name }}/{{sql_file_name}} state=absent
  sudo: yes

- name: migrate to new database
  shell: chdir=/var/www/{{ project_name }} python manage.py migrate 
  sudo: yes


- name: migrate to new database
  shell: chdir=/var/www/{{ project_name }} python manage.py migrate --fake
  sudo: yes

- name: restart httpd service
  service: name=httpd state=restarted
  sudo: yes

