---

- include: install_LAMPy_stack.yml
- include: install_4DB_mariadb_mongodb_redis_memcached.yml
- include: install_nginx_uwsgi_emperor_mode.yml

- name: deploy_storagon_servermain.yml
  hosts: all
  serial: 5 #concurent processing nodes

  vars:
    bitbucket_password: fill_me_in
    run_server_immediately: True
    httpd_port: 80
    nginx_port: 8080

  tasks:
    - name: clone repo
      git: repo=https://tranvietanh1991:{{ bitbucket_password }}@bitbucket.org/tranvietanh1991/storagon.git
      sudo: yes
      args:
        dest: /var/www/storagon
        update: no
      #no_log: True


    - name: create database
      mysql_db: name=storagon encoding=utf8 state=present
      sudo: yes
      #login_user=root login_password=''

    - name: create log dir
      command: sudo mkdir /var/www/storagon/log
      args:
        creates: /var/www/storagon/log

    - name: create sub log dir
      command: sudo mkdir /var/www/storagon/log/{{ item }}
      args:
        creates: /var/www/storagon/log/{{ item}}
      with_items:
        - celery

    - name: chmod log dir
      command: sudo chmod -R 777 /var/www/storagon/log

    - name: install django
      pip: name=django version=1.7
      sudo: yes

    - name: install django-cache-machine from git
      pip: name='git+https://github.com/jbalogh/django-cache-machine.git#egg=django-cache-machine'
      sudo: yes
      args:
        chdir: /var/www/storagon

    - name: install dependant lib
      pip: name={{ item }}
      sudo: yes
      with_items:
        - django-suit
        - django-suit-redactor
        - django-cors-headers
        - blinker
        - celery
        - django-celery
        - flower
        - pyyaml
        - django-oauth-toolkit
        - django-memcache-admin
        - djangorestframework
        - markdown
        - django-filter
        - djangorestframework-bulk
        - pyjwt
        - bunch
        - geoip2
        - bencode
        - pycrypto

    - name: django manage.py makemigrations
      command: sudo python manage.py makemigrations servermain
      args:
        chdir: /var/www/storagon

    - name: django manage.py migrate
      command: sudo python manage.py migrate
      args:
        chdir: /var/www/storagon

    - name: django manage.py test
      command: sudo python manage.py test
      args:
        chdir: /var/www/storagon

    - name: copy default admin user json fixture
      copy: src=files/default_admin_user.json dest=/var/www/storagon/default_admin_user.json
      sudo: yes

    - name: django load superuser (admin/admin)
      django_manage: command=loaddata app_path=/var/www/storagon fixtures=/var/www/storagon/default_admin_user.json
