---

- include: install_LAMPy_stack.yml
- include: install_4DB_mariadb_mongodb_redis_memcached.yml

- name: deploy_django_project_for_LAMPy4DB.yml
  hosts: all
  serial: 5 #concurent processing nodes

  vars:
    git_repo_url: https://tranvietanh1991:bitbucket_password@bitbucket.org/tranvietanh1991/orderus.git
    httpd_port: 80
    database_name: orderus
    project_name: orderus
    project_setting: settings.py
    pip_requirements: pip_requirements.yml
    makemigrations_modules: shop_module user_module system_configure


  tasks:
    - name: clone repo
      git: repo={{ git_repo_url }}
      sudo: yes
      args:
        dest: /var/www/{{ project_name }}
        update: no
      no_log: True

    - name: overide settings.py
      command: sudo cp -f {{ project_name }}/{{ project_setting }} {{ project_name }}/settings.py
      args:
        chdir: /var/www/{{ project_name }}
      when: project_setting != "settings.py"

    - name: create database
      mysql_db: name={{ database_name }} encoding=utf8 state=present
      sudo: yes

    - name: create log dir
      command: sudo mkdir /var/www/{{ project_name }}/log
      args:
        creates: /var/www/{{ project_name }}/log

    - name: install project pip requirements
      pip: requirements={{ pip_requirements }}
      sudo: yes
      args:
        chdir: /var/www/{{ project_name }}

    - name: django manage.py makemigrations
      command: sudo python manage.py makemigrations {{ makemigrations_modules }}
      args:
        chdir: /var/www/{{ project_name }}

    - name: django manage.py migrate
      command: sudo python manage.py migrate
      args:
        chdir: /var/www/{{ project_name }}

    - name: django manage.py test
      command: sudo python manage.py test
      args:
        chdir: /var/www/{{ project_name }}

    - name: chmod log dir
      command: sudo chmod -R 777 /var/www/{{ project_name }}/log

    - name: copy default admin user json fixture
      copy: src=files/default_admin_user.json dest=/var/www/{{ project_name }}/default_admin_user.json
      sudo: yes

    - name: django load superuser (admin/admin)
      django_manage: command=loaddata app_path=/var/www/{{ project_name }} fixtures=/var/www/{{ project_name }}/default_admin_user.json