---

- name: install Nginx + uwsgi emperor mode
  hosts: all
  serial: 3 #concurent processing nodes

  vars:
    nginx_port: 8080

  tasks:
    - include: tasks/install_nginx.yml #nginx_port=8080

    - include: tasks/install_uwsgi_emperor_mode.yml