---
- include: update_and_install_pip.yml

- name: install LAMP stack for python
  hosts: all
  serial: 3 #concurent processing nodes

  vars:
    httpd_port: 80

  tasks:
#    - name: start and enable httpd service
#      service: name=httpd state=running enabled=yes
#      sudo: yes
#      register: apache_result
    - include: tasks/install_apache_and_mod_wsgi.yml #httpd_port=80
    - include: tasks/install_mariadb_and_python_driver.yml
    - include: tasks/install_memcached_and_python_driver.yml

