---
#Install LAMP stack for python
- hosts: all
  serial: 3 #3 nodes at a time

  tasks:
    - name: install mariadb
      yum: name={{ item }} state=latest
      sudo: yes
      with_items:
        - mariadb-server
        - mariadb-devel

    - name: start and enable mariadb service
      service: name=mariadb state=started enabled=yes
      sudo: yes

    - name: install python driver using pip
      pip: name=mysql-python
      sudo: yes

    - name: install httpd and mod_wsgi
      yum: name={{ item }} state=latest
      sudo: yes
      with_items:
        - httpd
        - mod_wsgi

    - name: start and enable httpd service
      service: name=httpd state=started enabled=yes
      sudo: yes

    - name: install firewalld
      yum: name=firewalld state=latest
      sudo: yes

    - name: start and enable firewalld service
      service: name=firewalld state=started enabled=yes
      sudo: yes

    - name: open port for http
      firewalld: zone=public service=http permanent=true state=enabled immediate=true
      sudo: yes
    - name: open port for https
      firewalld: zone=public service=https permanent=true state=enabled immediate=true
      sudo: yes