---
- include: update_and_install_pip.yml

- name: install_docker_and_compose.yml
  hosts: all
  serial: 3 #concurent processing nodes

#sudo ansible-galaxy install franklinkim.docker
#sudo ansible-galaxy install franklinkim.docker-compose

  tasks:
    - name: install docker repo
      copy: src=files/docker.repo dest=/etc/yum.repos.d/docker.repo owner=root group=root mode=0644
      sudo: yes

    - name: install docker
      yum: name=docker state=latest
      sudo: yes

    - name: install docker-compose
      pip: name=docker-compose
      sudo: yes

    - name: start docker service
      service: name=docker state=started enabled=yes
      sudo: yes

    - name: allow docker containers to connect to internet
      command: firewall-cmd --permanent --zone=trusted --change-interface=docker0
      sudo: yes

    - name: open port for docker api
      firewalld: zone=trusted port=4243/tcp permanent=true state=enabled immediate=true
      sudo: yes