---

- name: test_clone_repo.yml
  hosts: all
  serial: 5 #concurent processing nodes

  tasks:
    - git: repo=https://tranvietanh1991:{{ bitbucket_password }}@bitbucket.org/tranvietanh1991/vietcomfund.git dest=~/vietcomfund
