---

- include: install_LAMPy_stack.yml
- include: install_4DB_mariadb_mongodb_redis_memcached.yml
- include: install_nginx_uwsgi_emperor_mode.yml

- name: test_clone_repo.yml
  hosts: all
  serial: 5 #concurent processing nodes

#  vars:
#    ch_dir: /var/www

  tasks:
    - name: clone repo
      git: repo=https://tranvietanh1991:{{ bitbucket_password }}@bitbucket.org/tranvietanh1991/storagon.git dest=/var/www/storagon
      #no_log: True

    - name: create database
      mysql_db: name=storagon encoding=utf8 state=present
      sudo: yes
      #login_user=root login_password=''

    - name: create log dir
      command: mkdir /var/www/storagon/log
      args:
        creates: /var/www/storagon/log

    - name: install django
      pip: name=django version=1.7
      sudo: yes

    - name: install django-cache-machine from git
      pip: name='git+https://github.com/jbalogh/django-cache-machine.git#egg=django-cache-machine'
      sudo: yes

    - name: install dependant lib
      pip: name={{ item }}
      sudo: yes
      with_items:
        - django-suit
        - django-suit-redactor
        - django-cors-headers
        - mongoengine
        - blinker
        - celery
        - django-celery
        - flower
        - pyyaml
        - django-oauth-toolkit
        - django-memcache-admin
        - djangorestframework
        - markdown
        - django-filter
        - djangorestframework-bulk
        - pyjwt
        - bunch
        - geoip2
        - bencode
        - pycrypto

    - name: django manage.py makemigrations
      command: python manage.py makemigrations servermain
      args:
        chdir: /var/www/storagon

    - name: django manage.py migrate
      command: python manage.py migrate
      args:
        chdir: /var/www/storagon

    - name: django manage.py test
      command: python manage.py test
      args:
        chdir: /var/www/storagon