---

- name: update yum packages and install pip
  hosts: all
  serial: 5 #concurent processing nodes

  tasks:
    - name: install dev lib
      command: sudo yum groupinstall -y development

    - name: upgrade all packages
      yum: name=* state=latest
      sudo: yes

    - name: install proper lib and tool
      yum: name={{ item }}
      sudo: yes
      with_items:
        - zlib-devel
        - openssl-devel
        - sqlite-devel
        - bzip2-devel
        - yum-utils
        - wget
        - vim
        - python-devel
        - screen
        - epel-release
        - firewalld
        - lsof


    - name: download easy_install source code
      command: wget --no-check-certificate https://pypi.python.org/packages/source/s/setuptools/setuptools-15.2.tar.gz
      args:
        chdir: ~
        creates: ~/setuptools-15.2.tar.gz

    - name: unrar easy_install source code
      command: tar -xvf setuptools-15.2.tar.gz
      args:
        chdir: ~
        creates: ~/setuptools-15.2/setup.py

    - name: install easy_install from source code
      command: sudo python setuptools-15.2/setup.py install
      args:
        chdir: ~
        creates: /usr/bin/easy_install

    - name: install pip using easy_install
      command: sudo easy_install pip
      args:
        creates: /usr/bin/pip

    - name: upgrade pip
      command: sudo pip install --upgrade pip
      args:
        creates: /usr/bin/virtualenv

    - name: install virtualenv using pip
      pip: name=virtualenv
      sudo: yes

    - name: start and enable firewalld service
      service: name=firewalld state=started enabled=yes
      sudo: yes