---

- name: update_storagon_servermain.yml
  hosts: all
  serial: 3 #concurent processing nodes

  vars:
    storagon_version: HEAD
    storagon_setting: settings.py
    storagon_httpd_conf: httpd.conf
    storagon_nginx_conf: nginx.conf
    storagon_uwsgi_conf: uwsgi_config.ini

  tasks:
    - name: fetch repo
      shell: echo {{bitbucket_password}} | sudo git fetch --all
      args:
        chdir: /var/www/storagon
      #no_log: True

    - name: update repo
      command: sudo git reset --hard origin/master
      args:
        chdir: /var/www/storagon

    - name: clear settings.pyc
      command: sudo rm -f storagon/settings.pyc
      args:
        chdir: /var/www/storagon

    - name: overide settings.py
      command: sudo cp -f storagon/{{ storagon_setting }} storagon/settings.py
      args:
        chdir: /var/www/storagon
      when: storagon_setting != "settings.py"

    - name: create static dir
      command: sudo mkdir /var/www/storagon/static
      args:
        creates: /var/www/storagon/static

    #servermain

    - name: overide httpd.conf
      command: sudo cp -f storagon/{{ storagon_httpd_conf }} /etc/httpd/conf/httpd.conf
      args:
        chdir: /var/www/storagon

    - name: restart httpd service
      service: name=httpd state=restarted
      sudo: yes

    - name: django manage.py collectstatic
      command: sudo python manage.py collectstatic --noinput -c
      args:
        chdir: /var/www/storagon

    #serverfile
    - name: overide nginx.conf
      command: sudo cp -f storagon/{{ storagon_nginx_conf }} /etc/nginx/nginx.conf
      args:
        chdir: /var/www/storagon

    - name: restart nginx service
      service: name=nginx state=restarted
      sudo: yes

    - name: copy/overide uwsgi config to vassals folder
      command: sudo cp -f storagon/{{ storagon_uwsgi_conf }} /etc/uwsgi/vassals/{{ storagon_uwsgi_conf }}
      args:
        chdir: /var/www/storagon

    - name: restart uwsgi service
      service: name=uwsgi state=restarted
      sudo: yes