---

- name: update_storagon_servermain.yml
  hosts: all
  serial: 3 #concurent processing nodes

  vars:
    bitbucket_password: fill_me_in
    storagon_version: origin/master
    storagon_setting: settings.py
    storagon_httpd_conf: httpd.conf
    storagon_nginx_conf: nginx.conf
    storagon_uwsgi_conf: uwsgi_config.ini
    storagon_static_dir: /var/www/storagon/static
    storagon_media_dir: /var/www/storagon/media

  tasks:
    - name: fetch repo
      shell: echo {{bitbucket_password}} | sudo git fetch --all
      args:
        chdir: /var/www/storagon
      no_log: True

    - name: update repo to specific version in {{ storagon_version }}
      command: sudo git reset --hard {{ storagon_version }}
      args:
        chdir: /var/www/storagon

    - name: clear settings.pyc
      command: sudo rm -f storagon/settings.pyc
      args:
        chdir: /var/www/storagon
        removes: storagon/settings.pyc

    - name: overide settings.py
      command: sudo cp -f storagon/{{ storagon_setting }} storagon/settings.py
      args:
        chdir: /var/www/storagon
      when: storagon_setting != "settings.py"

    - name: create static dir
      command: sudo mkdir {{ storagon_static_dir }}
      args:
        creates: '{{ storagon_static_dir }}'

    - name: create media dir
      command: sudo mkdir {{ storagon_media_dir }}
      args:
        creates: '{{ storagon_media_dir }}'

    - name: django manage.py makemigrations
      command: sudo python manage.py makemigrations
      args:
        chdir: /var/www/storagon

    - name: django manage.py migrate
      command: sudo python manage.py migrate
      args:
        chdir: /var/www/storagon

    - name: django manage.py test
      django_manage: command=test app_path=/var/www/storagon

    #servermain

    - name: overide httpd.conf
      command: sudo cp -f storagon/{{ storagon_httpd_conf }} /etc/httpd/conf/httpd.conf
      args:
        chdir: /var/www/storagon

    - name: restart httpd service
      service: name=httpd state=restarted
      sudo: yes

    - name: django manage.py collectstatic
      command: sudo python manage.py collectstatic --noinput -c
      args:
        chdir: /var/www/storagon

    #serverfile
    - name: overide nginx.conf
      command: sudo cp -f storagon/{{ storagon_nginx_conf }} /etc/nginx/nginx.conf
      args:
        chdir: /var/www/storagon

    - name: restart nginx service
      service: name=nginx state=restarted
      sudo: yes

    - name: copy/overide uwsgi config to vassals folder
      command: sudo cp -f storagon/{{ storagon_uwsgi_conf }} /etc/uwsgi/vassals/{{ storagon_uwsgi_conf }}
      args:
        chdir: /var/www/storagon

    - name: restart uwsgi service
      service: name=uwsgi state=restarted
      sudo: yes

    #celery
    - name: mkdir /var/run/celery
      command: sudo mkdir /var/run/celery
      args:
        creates: /var/run/celery

    - name: mkdir /var/log/celery
      command: sudo mkdir /var/log/celery
      args:
        creates: /var/log/celery

    - name: stop celery worker
      command: sudo celery multi stop storagon_worker -A storagon -l info --pidfile="/var/run/celery/%n.pid"
      args:
        chdir: /var/www/storagon

    - name: start celery worker with beat enable
      command: sudo celery multi start storagon_worker -A storagon --beat -l info --pidfile="/var/run/celery/%n.pid" --logfile="/var/log/celery/%n.log"
      args:
        chdir: /var/www/storagon