---

- hosts: all
  serial: 5 #5 nodes at a time

  tasks:
    - name: install dev lib
      command: sudo yum groupinstall -y development

    - name: upgrade all packages
      yum: name=* state=latest
#      sudo_user: root
      sudo: yes

    - name: install proper lib and tool
      yum: name={{ item }} state=latest
#      sudo_user: root
      sudo: yes
      with_items:
        - zlib-devel
        - openssl-devel
        - sqlite-devel
        - bzip2-devel
        - yum-utils
        - wget
        - vim
        - python-devel
        - screen
        - epel-release

    - name: install pip
      yum: name=python-pip state=latest
#      sudo_user: root
      sudo: yes